export const company = {
  name: 'A.S. Consulting',
  person: 'Andrzej Sadowski',
  email: 'andrzej@sadowski-consulting.pl',
  phone: '+48 601 240 928',
  phoneHref: '+48601240928',
};

export const services = [
  {
    id: 'audyty', number: '01', title: 'Audyty', short: 'Zobacz pełny obraz.',
    path: 'oferta/audyty', icon: 'scan',
    description: 'Sprawdzenie standardów dealerskich. Rzetelny punkt wyjścia do dalszych decyzji.',
    eyebrow: 'Audyty standardów dealerskich',
    heading: 'Audyty standardów', emphasis: 'dealerskich.',
    intro: 'Audyty standardów dealerskich na zlecenie producentów samochodów. Uporządkowane spojrzenie na to, jak działa sieć i w jakim stopniu spełnia określone wymagania.',
    audience: 'Producenci samochodów i organizacje zarządzające siecią dealerską.',
    result: 'Ocena zgodności z uzgodnionymi standardami dealerskimi.',
    openingTitle: 'Weryfikacja standardów producenta.',
    opening: 'Spójność sieci zaczyna się od wspólnego rozumienia wymagań. Audyt pozwala przyjrzeć się rzeczywistemu funkcjonowaniu dealerstwa w odniesieniu do standardów producenta.',
    areas: [
      ['Wymagania producenta', 'Punktem odniesienia są standardy obowiązujące w danej sieci dealerskiej.'],
      ['Funkcjonowanie dealerstwa', 'Ocena opiera się na zakresie uzgodnionym dla konkretnego zlecenia.'],
      ['Zgodność ze standardami', 'Uporządkowanie obserwacji ułatwia zrozumienie obszarów wymagających uwagi.'],
    ],
    process: [
      ['Ustalenie zakresu', 'Rozmowa o standardach, celu audytu i specyfice sieci.'],
      ['Przeprowadzenie audytu', 'Weryfikacja dealerstwa w odniesieniu do uzgodnionych wymagań.'],
      ['Omówienie wyników', 'Przedstawienie ustaleń jako podstawy do dalszych działań.'],
    ],
    faq: [
      ['Dla kogo realizowane są audyty?', 'Audyty standardów dealerskich realizowane są na zlecenie producentów samochodów. Zakres konkretnego projektu ustalamy podczas rozmowy.'],
      ['Czy audyt standardów to Program Rozwoju Dealera?', 'To dwa różne zakresy pracy. Audyt standardów odnosi się do wymagań producenta. Audyt w Programie Rozwoju Dealera służy analizie potencjału, organizacji i efektywności działów posprzedażnych.'],
      ['Jak ustalany jest zakres i koszt?', 'Punktem wyjścia jest cel audytu, standardy danej sieci i zakres zlecenia. Skontaktuj się, aby omówić szczegóły projektu.'],
    ],
    next: 'program-rozwoju-dealera',
  },
  {
    id: 'doradztwo', number: '02', title: 'Doradztwo', short: 'Nadaj decyzjom kierunek.',
    path: 'oferta/doradztwo', icon: 'compass',
    description: 'Potencjał rynku, strategia rozwoju i organizacja dealerstwa. Decyzje osadzone w realiach biznesu.',
    eyebrow: 'Doradztwo dla dealerów',
    heading: 'Doradztwo dla', emphasis: 'branży motoryzacyjnej.',
    intro: 'Rozwój dealerstwa wymaga spojrzenia na rynek, organizację i ludzi jednocześnie. Pomagam połączyć te perspektywy w przemyślane decyzje biznesowe.',
    audience: 'Właściciele i osoby zarządzające dealerstwami oraz działami obsługi posprzedażnej.',
    result: 'Kierunek działania dopasowany do potencjału rynku i organizacji.',
    openingTitle: 'Analiza rynku i organizacji dealerstwa.',
    opening: 'Nowa inwestycja, zmiana organizacji czy plan rozwoju powinny wynikać z analizy. Doradztwo łączy perspektywę rynku lokalnego z praktyczną wiedzą o funkcjonowaniu dealerstwa.',
    areas: [
      ['Potencjał rynku lokalnego', 'Analiza możliwości sprzedaży usług serwisowych i części zamiennych na lokalnym rynku dealera.'],
      ['Strategia i budżet', 'Tworzenie strategii rozwoju oraz trzyletnich budżetów jako podstawy do planowania działań.'],
      ['Obiekty dealerskie', 'Analizy funkcjonalne planów obiektów z uwzględnieniem organizacji pracy dealerstwa.'],
      ['Kadra zarządzająca', 'Konsultacje dotyczące zatrudniania osób na stanowiska kierownicze.'],
    ],
    process: [
      ['Kontekst i cel', 'Zaczynamy od sytuacji dealerstwa oraz decyzji, przed którą stoisz.'],
      ['Analiza możliwości', 'Przyglądamy się danym, rynkowi i uwarunkowaniom organizacyjnym.'],
      ['Kierunek działania', 'Omawiamy wnioski i rozwiązania odpowiadające celowi współpracy.'],
    ],
    faq: [
      ['Czy możemy omówić jeden konkretny problem?', 'Tak. Doradztwo może dotyczyć wybranego zagadnienia z oferty, na przykład potencjału rynku, planu obiektu lub zatrudnienia kadry zarządzającej.'],
      ['Czy oferta obejmuje przygotowanie budżetu?', 'Tak. W ramach doradztwa przygotowywane są strategie rozwoju i trzyletnie budżety. Szczegółowy zakres zależy od sytuacji dealerstwa.'],
      ['Co przygotować przed pierwszą rozmową?', 'Krótko opisz swoją organizację, obszar wymagający wsparcia i decyzję, którą chcesz podjąć. Zakres potrzebnych danych ustalimy w odniesieniu do projektu.'],
    ],
    next: 'szkolenia',
  },
  {
    id: 'program-rozwoju-dealera', number: '03', title: 'Program Rozwoju Dealera', short: 'Przełóż potencjał na działanie.',
    path: 'oferta/program-rozwoju-dealera', icon: 'growth',
    description: 'Autorski program: od diagnozy, przez szkolenia, po monitorowanie zmian w codziennej pracy.',
    eyebrow: 'Autorski Program Rozwoju Dealera',
    heading: 'Program Rozwoju', emphasis: 'Dealera.',
    intro: 'Efektywniejszy serwis. Lepsza współpraca z działem części. Sprawniejsza obsługa klienta. Program łączy analizę organizacji, praktyczne szkolenia i monitorowanie wyników.',
    audience: 'Właściciele dealerstw, dyrektorzy oraz kierownicy serwisu i działu części.',
    result: 'Plan działań, rozwój kompetencji kierowników i trzymiesięczny etap monitoringu.',
    openingTitle: 'Organizacja serwisu i działu części.',
    opening: 'Sprawnie działający serwis wspiera rozwój działu części. Dobra obsługa wzmacnia wiarygodność dealera i lojalność klientów. Program pomaga spojrzeć na te obszary jak na jeden, współpracujący organizm.',
    areas: [
      ['Dane i narzędzia', 'Dostęp do informacji o sprzedaży i zysku, bieżące wyniki działów oraz wykorzystanie oprogramowania.'],
      ['Organizacja i komunikacja', 'Rzeczywista struktura firmy, podział odpowiedzialności oraz przepływ informacji handlowych i marketingowych.'],
      ['Ludzie i wydajność', 'Wydajność pracowników oraz praktyczne kompetencje kierowników w zarządzaniu działami.'],
      ['Potencjał posprzedaży', 'Możliwości rozwoju serwisu i części, jakość obsługi oraz dostępność usług i towarów.'],
    ],
    process: [
      ['Audyt', 'Analiza danych, organizacji, komunikacji i wydajności. Identyfikacja możliwości rozwoju oraz obszarów wymagających zmian lub doinwestowania.'],
      ['Prezentacja', 'Omówienie wniosków z właścicielem. To moment na ocenę celowości szkoleń i podjęcie decyzji o dalszych krokach.'],
      ['Szkolenia', 'Praktyczna praca z kierownikami: analiza KPI, decyzje zarządcze, organizacja pracy i jakość obsługi.'],
      ['Monitoring', 'Przez trzy miesiące kierownicy przesyłają dane co tydzień. Wyniki omawiane są na comiesięcznych spotkaniach.'],
    ],
    faq: [
      ['Na czym koncentruje się program?', 'Na efektywności działów obsługi posprzedażnej, przede wszystkim serwisu i działu części. Ważne są również jakość obsługi, przepływ informacji i dostępność usług.'],
      ['Czy po audycie trzeba przejść do szkoleń?', 'Prezentacja wyników audytu pozwala właścicielowi ocenić zasadność szkoleń i podjąć decyzję o kolejnym etapie.'],
      ['Jak wygląda monitoring?', 'Etap monitoringu trwa trzy miesiące. Kierownicy przesyłają dane na koniec każdego tygodnia, a wyniki są omawiane na spotkaniach raz w miesiącu.'],
      ['Jakich efektów dotyczy praca?', 'Celem jest poprawa wydajności, sprzedaży, jakości obsługi, dostępności usług i rentowności dealerstwa. Rzeczywiste rezultaty zależą od sytuacji firmy i wdrożenia zmian.'],
    ],
    next: 'szkolenia',
  },
  {
    id: 'szkolenia', number: '04', title: 'Szkolenia', short: 'Wzmocnij ludzi, którzy zarządzają.',
    path: 'oferta/szkolenia', icon: 'people',
    description: 'Praktyczna wiedza dla kierowników serwisu i działu części. Od codziennej organizacji po analizę KPI.',
    eyebrow: 'Szkolenia dla kadry zarządzającej',
    heading: 'Szkolenia dla', emphasis: 'kadry zarządzającej.',
    intro: 'Praktyczne zarządzanie serwisem mechanicznym i działem części zamiennych. Tematy wynikające z codziennych decyzji, odpowiedzialności i wyzwań kierowników.',
    audience: 'Kierownicy serwisu mechanicznego oraz działów części zamiennych.',
    result: 'Praktyczna wiedza z organizacji pracy, zarządzania sprzedażą i monitorowania KPI.',
    openingTitle: 'Zarządzanie serwisem i częściami.',
    opening: 'Sama liczba w raporcie nie zmienia sposobu pracy. Podczas szkoleń łączę analizę parametrów z decyzjami kierownika i ich wpływem na wydajność, dostępność oraz jakość obsługi.',
    areas: [
      ['Serwis mechaniczny', 'Zarządzanie biurem obsługi klienta i warsztatem, współpraca serwisu z działem części oraz kluczowe parametry pracy.'],
      ['Części zamienne', 'Zarządzanie magazynem, sprzedażą wewnętrzną i zewnętrzną, w tym hurtową, oraz monitoring wyników działu.'],
    ],
    process: [
      ['Wybór zakresu', 'Ustalamy, którego działu i jakich zagadnień ma dotyczyć szkolenie.'],
      ['Praktyczna wiedza', 'Łączymy pojęcia i metody zarządzania z sytuacjami z codziennej pracy.'],
      ['Perspektywa kierownika', 'Odnosimy analizę KPI do decyzji, organizacji zespołu i jakości obsługi.'],
    ],
    faq: [
      ['Dla kogo przeznaczone są szkolenia?', 'Dla osób zarządzających serwisem mechanicznym oraz działem części zamiennych. Zakres obejmuje organizację pracy, sprzedaż i kluczowe parametry działania tych działów.'],
      ['Czy szkolenia obejmują zarządzanie magazynem?', 'Tak. Jest to część programu dotyczącego zarządzania działem części zamiennych, obok sprzedaży wewnętrznej, zewnętrznej i monitorowania KPI.'],
      ['Czy szkolenie może być częścią szerszej współpracy?', 'Tak. Szkolenia są jednym z etapów Programu Rozwoju Dealera, który obejmuje również audyt, prezentację wniosków i monitoring.'],
    ],
    next: 'program-rozwoju-dealera',
  },
];

export const clients = [
  { name: 'BMW Polska', field: 'Szkolenia', period: '2005', text: 'Indywidualne szkolenia dealerów.' },
  { name: 'Renault Polska', field: 'Szkolenia i audyty', period: 'Współpraca od 2005', text: 'Projekty szkoleniowe i audytowe w sieci dealerskiej.' },
  { name: 'Ford Polska', field: 'Szkolenia i audyty', period: '2006–2007', text: 'Wsparcie sieci w obszarze szkoleń i audytów.' },
  { name: 'Toyota Motor Poland', field: 'Audyty standardów', period: '2007', text: 'Audyt standardów dealerskich w ramach współpracy z Urban Science.' },
  { name: 'Nissan Central Europe Poland', field: 'Szkolenia i audyty', period: 'Współpraca od 2007', text: 'Szkolenia i audyty dla sieci dealerskiej.' },
  { name: 'Renault Trucks Polska', field: 'Szkolenia i audyty', period: '2007–2009', text: 'Projekty dla dealerów w segmencie pojazdów użytkowych.' },
  { name: 'Honda Poland', field: 'Szkolenia', period: 'Współpraca od 2008', text: 'Szkolenia i współpraca z siecią dealerską.' },
  { name: 'Tata Motors', field: 'Audyty standardów', period: '2009', text: 'Audyt standardów dealerskich w ramach współpracy z Urban Science.' },
];

export const career = [
  ['2005', 'A.S. Consulting', 'Doradca ds. rozwoju dealerów', 'Własna praktyka doradcza i autorski Program Rozwoju Dealera.'],
  ['2004–2005', 'Bawaria Motors · BMW', 'Dyrektor zarządzający', 'Perspektywa zarządzania całym dealerstwem.'],
  ['2002–2003', 'Summit Auto Poland', 'Dyrektor ds. rozwoju', 'Doświadczenie w rozwoju organizacji dealerskiej.'],
  ['1997–2001', 'Ford Auto Plaza', 'Dyrektor działu części', 'Zarządzanie jednym z kluczowych obszarów obsługi posprzedażnej.'],
  ['1991–1996', 'Nissan–Ballaun', 'Od sprzedawcy do kierownika', 'Droga od sprzedaży samochodów do kierowania zakładem dealerskim.'],
];
